# Generated by Django 4.0.2 on 2022-02-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_question_text_question_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questionc',
        ),
    ]
